import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-white">
      <Navbar />
      <main className="pt-32 pb-20">
        <div className="container mx-auto px-4 md:px-6 max-w-3xl">
          <h1 className="display-2 mb-4">Terms of Service</h1>
          <p className="text-sm text-gray-400 mb-12">Last updated: February 2026</p>

          <div className="space-y-10 text-gray-600 leading-relaxed">
            <section>
              <h2 className="text-xl font-serif font-bold text-gray-900 mb-3">1. Acceptance of Terms</h2>
              <p>By accessing and using Jasmyn AI ("Company") services, you accept and agree to be bound by the terms and provision of this agreement.</p>
            </section>

            <section>
              <h2 className="text-xl font-serif font-bold text-gray-900 mb-3">2. Use License</h2>
              <p className="mb-3">Permission is granted to temporarily access and use the materials on Jasmyn AI's platform for personal or commercial use in accordance with your subscription plan. Under this license you may not:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Modify or copy the proprietary software or materials</li>
                <li>Use the materials for any purpose not permitted by your subscription plan</li>
                <li>Attempt to decompile or reverse engineer any software contained on Jasmyn AI's platform</li>
                <li>Remove any copyright or other proprietary notations from the materials</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-serif font-bold text-gray-900 mb-3">3. Service Description</h2>
              <p className="mb-3">Jasmyn AI provides AI-powered marketing automation services including but not limited to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Social media management and content creation</li>
                <li>Ad campaign creation and optimization</li>
                <li>Email marketing flow automation</li>
                <li>Business analytics and marketing strategy</li>
                <li>UGC-style creative generation</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-serif font-bold text-gray-900 mb-3">4. Client Responsibilities</h2>
              <p className="mb-3">Clients are responsible for:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Providing accurate and complete information</li>
                <li>Timely feedback and approvals</li>
                <li>Payment of fees as agreed</li>
                <li>Compliance with applicable laws and regulations</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-serif font-bold text-gray-900 mb-3">5. Intellectual Property</h2>
              <p>Content and creatives generated by Jasmyn AI for your business are yours to use. The Company retains ownership of the underlying AI technology, platform, and proprietary systems.</p>
            </section>

            <section>
              <h2 className="text-xl font-serif font-bold text-gray-900 mb-3">6. Payment Terms</h2>
              <p>Subscription fees are billed monthly. Late payments may result in suspension of services. All fees are non-refundable except as specified in our Cancellation & Refund Policy.</p>
            </section>

            <section>
              <h2 className="text-xl font-serif font-bold text-gray-900 mb-3">7. Limitation of Liability</h2>
              <p>In no event shall Jasmyn AI or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Jasmyn AI's platform, even if Jasmyn AI or a Jasmyn AI authorized representative has been notified orally or in writing of the possibility of such damage.</p>
            </section>

            <section>
              <h2 className="text-xl font-serif font-bold text-gray-900 mb-3">8. Revisions and Errata</h2>
              <p>The materials appearing on Jasmyn AI's platform could include technical, typographical, or photographic errors. Jasmyn AI does not warrant that any of the materials on its platform are accurate, complete, or current.</p>
            </section>

            <section>
              <h2 className="text-xl font-serif font-bold text-gray-900 mb-3">9. Governing Law</h2>
              <p>These terms and conditions are governed by and construed in accordance with the laws of Wyoming, USA, and you irrevocably submit to the exclusive jurisdiction of the courts in that state or location.</p>
            </section>

            <section>
              <h2 className="text-xl font-serif font-bold text-gray-900 mb-3">10. Contact Information</h2>
              <p>If you have any questions about these Terms of Service, please contact us at:</p>
              <div className="mt-3 space-y-1">
                <p>Jasmyn AI</p>
                <p>Email: <a href="mailto:hello@jasmyn.ai" className="text-primary hover:underline">hello@jasmyn.ai</a></p>
              </div>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
